using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEngine;
#if UNITY_EDITOR
using UnityEditor;
#endif

public static class ContextPipelineTracer
{
    private const string ReportTitle = "CONTEXT PIPELINE TRACE REPORT";
    private const string RuntimeChatUIPath = "Assets/_Project/Scripts/Dialogue/RuntimeChatUI.cs";
    private const string DialogueManagerPath = "Assets/_Project/Scripts/Dialogue/DialogueManager.cs";
    private const string ContextRetrieverPath = "Assets/_Project/Scripts/AI/ContextRetriever.cs";
    private const string ContextSnapshotPath = "Assets/_Project/Scripts/AI/ContextSnapshot.cs";
    private const string PromptBuilderPath = "Assets/_Project/Scripts/AI/PromptBuilder.cs";
    private const string OpenAIClientPath = "Assets/_Project/Scripts/AI/OpenAIClient.cs";
    private const string MockLLMClientPath = "Assets/_Project/Scripts/AI/MockLLMClient.cs";

    public static void TraceCurrentContextPipeline(DialogueManager dialogueManager, string runtimeChatInput)
    {
        TraceData data = BuildTraceData(dialogueManager, runtimeChatInput);
        List<ValueTraceRow> valueRows = BuildValueRows(data);
        string report = BuildReport(data, valueRows);

        Debug.Log(report);
        SaveReport(report);
    }

    private static TraceData BuildTraceData(DialogueManager providedDialogueManager, string runtimeChatInput)
    {
        TraceData data = new TraceData();
        data.dialogueManager = providedDialogueManager != null ? providedDialogueManager : FindDialogueManager();
        data.runtimeChatInput = runtimeChatInput ?? string.Empty;

        if (data.dialogueManager != null)
        {
            data.contextRetriever = data.dialogueManager.DebugContextRetriever != null ? data.dialogueManager.DebugContextRetriever : ResolveContextRetriever();
            data.memoryStore = data.dialogueManager.DebugConversationMemoryStore != null ? data.dialogueManager.DebugConversationMemoryStore : ResolveMemoryStore();
            data.openAIClient = data.dialogueManager.DebugOpenAIClient;
            data.mockLLMClient = data.dialogueManager.DebugFallbackMockLLMClient;
            data.currentNpc = data.dialogueManager.currentNpc;
            data.currentNpcTransform = data.dialogueManager.currentNpcTransform;
            data.lastPlayerMessage = data.dialogueManager.LastPlayerMessage ?? string.Empty;
            data.snapshot = data.dialogueManager.LastContextSnapshot;
            data.finalPrompt = data.dialogueManager.LastGeneratedPrompt ?? string.Empty;
        }
        else
        {
            data.contextRetriever = ResolveContextRetriever();
            data.memoryStore = ResolveMemoryStore();
        }

        if (data.snapshot != null)
        {
            data.snapshotOrigin = "DialogueManager.LastContextSnapshot captured after DialogueManager.SendPlayerMessage called ContextRetriever.BuildSnapshot.";
        }
        else if (data.contextRetriever != null && data.currentNpc != null)
        {
            data.snapshot = data.contextRetriever.BuildSnapshot(data.currentNpc, data.currentNpcTransform, data.lastPlayerMessage);
            data.snapshotOrigin = "TRACE-ONLY: rebuilt by ContextRetriever.BuildSnapshot for this report because DialogueManager.LastContextSnapshot was empty.";
            data.usedTraceOnlySnapshot = true;
        }
        else
        {
            data.snapshotOrigin = BuildSnapshotUnavailableReason(data.contextRetriever, data.currentNpc);
        }

        if (data.snapshot != null)
        {
            data.reconstructedPrompt = PromptBuilder.BuildPrompt(data.snapshot);
        }

        if (!string.IsNullOrEmpty(data.finalPrompt))
        {
            data.finalPromptOrigin = "DialogueManager.LastGeneratedPrompt. This is the final prompt most recently passed to ILLMClient.SendPrompt.";
            data.promptWasActuallySent = data.dialogueManager != null && data.dialogueManager.LastContextSnapshot != null;
        }
        else if (!string.IsNullOrEmpty(data.reconstructedPrompt))
        {
            data.finalPrompt = data.reconstructedPrompt;
            data.finalPromptOrigin = "TRACE-ONLY: generated by PromptBuilder.BuildPrompt(snapshot) for this report. It has not been sent to the LLM by the trace button.";
        }
        else
        {
            data.finalPromptOrigin = "NOT AVAILABLE: no final prompt exists and no ContextSnapshot was available to reconstruct one.";
        }

        data.playerState = data.snapshot != null && data.snapshot.playerState != null ? data.snapshot.playerState : FindPlayerState();
        data.worldState = data.snapshot != null && data.snapshot.worldState != null ? data.snapshot.worldState : ResolveWorldState();
        data.sceneObjects = UnityEngine.Object.FindObjectsByType<SceneContextObject>(FindObjectsSortMode.None);
        data.knowledgeEntries = GetKnowledgeEntries(data.contextRetriever);
        data.knowledgeRetrievalEvidence = GetKnowledgeRetrievalEvidence(data);
        return data;
    }

    private static string BuildReport(TraceData data, List<ValueTraceRow> valueRows)
    {
        StringBuilder builder = new StringBuilder();
        builder.AppendLine(ReportTitle);
        builder.AppendLine("Generated At: " + DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss"));
        builder.AppendLine("Persistent Data Path: " + Application.persistentDataPath);
        builder.AppendLine("Snapshot Origin: " + SafeText(data.snapshotOrigin, "NOT AVAILABLE: no snapshot origin."));
        builder.AppendLine("Final Prompt Origin: " + SafeText(data.finalPromptOrigin, "NOT AVAILABLE: no prompt origin."));
        builder.AppendLine("Prompt Was Actually Sent By DialogueManager: " + data.promptWasActuallySent);
        builder.AppendLine();

        AppendCallChain(builder, data);
        AppendValuePropagationMatrix(builder, valueRows);
        AppendPromptAssemblyProof(builder, data);
        AppendKnowledgeRetrievalDecisions(builder, data);
        AppendHardcodedVsDynamic(builder, data);
        AppendSourceCodeReferences(builder, data);
        AppendAutomaticMarkerTest(builder, valueRows);

        return builder.ToString();
    }

    private static void AppendCallChain(StringBuilder builder, TraceData data)
    {
        builder.AppendLine("=== CALL CHAIN ===");

        AppendCallStep(
            builder,
            "1",
            "RuntimeChatUI",
            "DrawInput() / Send()",
            RuntimeChatUIPath,
            "Data enters: visible button click; current RuntimeChatUI inputText = " + FormatValue(data.runtimeChatInput) + "; last sent player message = " + FormatValue(data.lastPlayerMessage) + ".",
            "Data exits: [TRACE CONTEXT PIPELINE] calls ContextPipelineTracer.TraceCurrentContextPipeline(dialogueManager, inputText). Normal chat send calls DialogueManager.SendPlayerMessage(text).");

        AppendCallStep(
            builder,
            "2",
            "DialogueManager",
            "SendPlayerMessage(string text)",
            DialogueManagerPath,
            "Data enters: currentNpc = " + DescribeNpc(data.currentNpc) + "; currentNpcTransform = " + DescribeTransform(data.currentNpcTransform) + "; text = " + FormatValue(data.lastPlayerMessage) + ".",
            "Data exits: LastContextSnapshot = " + DescribeSnapshot(data.snapshot) + "; LastGeneratedPrompt length = " + GetLengthText(data.finalPrompt) + "; LastIntendedLLMProvider = " + GetLastIntendedProvider(data) + "; LastActualLLMProvider = " + GetLastActualProvider(data) + ".");

        AppendCallStep(
            builder,
            "3",
            "ContextRetriever",
            "BuildSnapshot(NPCProfile npc, Transform npcTransform, string playerMessage)",
            ContextRetrieverPath,
            "Data enters: npc = " + DescribeNpc(data.currentNpc) + "; npcTransform = " + DescribeTransform(data.currentNpcTransform) + "; playerMessage = " + FormatValue(data.lastPlayerMessage) + "; KnowledgeBase = " + DescribeKnowledgeBase(data.contextRetriever) + ".",
            "Data exits: " + DescribeSnapshot(data.snapshot) + ".");

        AppendCallStep(
            builder,
            "4",
            "ContextSnapshot",
            "public fields filled by ContextRetriever.BuildSnapshot",
            ContextSnapshotPath,
            "Data enters: direct assignments from NPCProfile, PlayerState, WorldState, nearby SceneContextObjects, retrieved KnowledgeEntries, recent dialogue history, and playerMessage.",
            "Data exits: npcProfile/playerState/worldState/playerMessage plus lists: nearbyObjects=" + GetCountText(data.snapshot != null ? data.snapshot.nearbyObjects : null) + ", retrievedKnowledge=" + GetCountText(data.snapshot != null ? data.snapshot.retrievedKnowledge : null) + ", recentDialogueHistory=" + GetCountText(data.snapshot != null ? data.snapshot.recentDialogueHistory : null) + ".");

        AppendCallStep(
            builder,
            "5",
            "PromptBuilder",
            "BuildPrompt(ContextSnapshot snapshot)",
            PromptBuilderPath,
            "Data enters: ContextSnapshot = " + DescribeSnapshot(data.snapshot) + ".",
            "Data exits: reconstructed prompt length = " + GetLengthText(data.reconstructedPrompt) + "; reconstructed prompt equals final prompt = " + PromptEquals(data.finalPrompt, data.reconstructedPrompt) + ".");

        AppendCallStep(
            builder,
            "6",
            GetProviderClassName(data),
            "SendPrompt(string prompt, Action<string> onResponse)",
            GetProviderFilePath(data),
            GetProviderInputText(data),
            "Data exits: intended provider = " + GetLastIntendedProvider(data) + "; actual provider = " + GetLastActualProvider(data) + "; " + GetProviderResultText(data) + ".");

        builder.AppendLine();
    }

    private static void AppendCallStep(StringBuilder builder, string number, string className, string methodName, string filePath, string enters, string exits)
    {
        builder.AppendLine(number + ". " + className + "." + methodName);
        builder.AppendLine("   Class name: " + className);
        builder.AppendLine("   Method name: " + methodName);
        builder.AppendLine("   File path: " + filePath);
        builder.AppendLine("   " + enters);
        builder.AppendLine("   " + exits);
    }

    private static void AppendValuePropagationMatrix(StringBuilder builder, List<ValueTraceRow> rows)
    {
        builder.AppendLine("=== VALUE PROPAGATION MATRIX ===");

        if (rows == null || rows.Count == 0)
        {
            builder.AppendLine("NOT AVAILABLE: no value rows could be built.");
            builder.AppendLine();
            return;
        }

        for (int i = 0; i < rows.Count; i++)
        {
            ValueTraceRow row = rows[i];
            builder.AppendLine("Value #" + (i + 1));
            builder.AppendLine("- Source object: " + row.sourceObject);
            builder.AppendLine("- Source field: " + row.sourceField);
            builder.AppendLine("- Source value: " + row.sourceValue);
            builder.AppendLine("- Snapshot field where it appears: " + row.snapshotField);
            builder.AppendLine("- Does it appear in final prompt? " + row.appearsInPrompt);
            builder.AppendLine("- Exact prompt excerpt where it appears: " + row.promptExcerpt);
            builder.AppendLine("- Marker: " + row.marker);

            if (!string.IsNullOrEmpty(row.note))
            {
                builder.AppendLine("- Note: " + row.note);
            }
        }

        builder.AppendLine();
    }

    private static void AppendPromptAssemblyProof(StringBuilder builder, TraceData data)
    {
        builder.AppendLine("=== PROMPT ASSEMBLY PROOF ===");

        if (data.snapshot == null)
        {
            builder.AppendLine("NOT AVAILABLE: no ContextSnapshot is available.");
            builder.AppendLine();
            return;
        }

        AppendPromptSectionProof(builder, data, "CURRENT NPC", "VISIBLE PLAYER STATE", "snapshot.npcProfile.GetProfileContextText()");
        AppendPromptSectionProof(builder, data, "VISIBLE PLAYER STATE", "PLAYER DISCOVERED FACTS", "snapshot.playerState.equippedOutfit, visibleHeldItem, visibleStatusTags");
        AppendPromptSectionProof(builder, data, "PLAYER DISCOVERED FACTS", "NPC STATE TOWARD PLAYER", "snapshot.playerState.knownFacts, completedActions, heldItems");
        AppendPromptSectionProof(builder, data, "NPC STATE TOWARD PLAYER", "LOCAL ENVIRONMENT", "snapshot.npcState.mood, trustToPlayer, personalEvents");
        AppendPromptSectionProof(builder, data, "LOCAL ENVIRONMENT", "PUBLIC WORLD STATE", "snapshot.nearbyObjects[i].GetContextText()");
        AppendPromptSectionProof(builder, data, "PUBLIC WORLD STATE", "RECENT RELEVANT EVENTS", "snapshot.worldState.GetWorldStateText()");
        AppendPromptSectionProof(builder, data, "RECENT RELEVANT EVENTS", "RETRIEVED KNOWLEDGE", "snapshot.recentRelevantEvents[i].GetShortText()");
        AppendPromptSectionProof(builder, data, "RETRIEVED KNOWLEDGE", "RECENT MEMORY", "snapshot.retrievedKnowledge[i].GetKnowledgeText()");
        AppendPromptSectionProof(builder, data, "RECENT MEMORY", "CURRENT PLAYER MESSAGE", "snapshot.recentDialogueHistory[i].speaker/text filtered by active npcId");
        AppendPromptSectionProof(builder, data, "CURRENT PLAYER MESSAGE", "RESPONSE RULES", "snapshot.playerMessage");
        AppendPromptSectionProof(builder, data, "RESPONSE RULES", "FINAL CHECK BEFORE ANSWERING:", "hardcoded response rules for this MVP context layer");

        builder.AppendLine("Prompt equality proof:");
        builder.AppendLine("- PromptBuilder.BuildPrompt(snapshot) == DialogueManager.LastGeneratedPrompt: " + PromptEquals(data.finalPrompt, data.reconstructedPrompt));
        builder.AppendLine("- If true, the final prompt was assembled from the captured ContextSnapshot by PromptBuilder.BuildPrompt(snapshot).");
        builder.AppendLine();
    }

    private static void AppendPromptSectionProof(StringBuilder builder, TraceData data, string sectionName, string nextSectionName, string source)
    {
        builder.AppendLine("Prompt section: " + sectionName);
        builder.AppendLine("Source: " + source);
        builder.AppendLine("Result:");
        builder.AppendLine(ExtractPromptSection(data.finalPrompt, sectionName, nextSectionName));
        builder.AppendLine();
    }

    private static void AppendKnowledgeRetrievalDecisions(StringBuilder builder, TraceData data)
    {
        builder.AppendLine("=== KNOWLEDGE RETRIEVAL DECISIONS ===");

        if (data.contextRetriever == null)
        {
            builder.AppendLine("NOT AVAILABLE: ContextRetriever was not found.");
            builder.AppendLine();
            return;
        }

        if (data.contextRetriever.knowledgeBase == null)
        {
            builder.AppendLine("NOT AVAILABLE: ContextRetriever.knowledgeBase is not assigned.");
            builder.AppendLine();
            return;
        }

        builder.AppendLine("KnowledgeBase: " + DescribeKnowledgeBase(data.contextRetriever));
        builder.AppendLine("Decision model: allowed AND one strong activation AND score >= 7; local/NPC profile/importance do not activate by themselves.");

        if (data.knowledgeRetrievalEvidence == null || data.knowledgeRetrievalEvidence.Count == 0)
        {
            builder.AppendLine("No KnowledgeEntry records were available.");
            builder.AppendLine();
            return;
        }

        List<ContextRetriever.DebugKnowledgeRetrievalEntry> entries = new List<ContextRetriever.DebugKnowledgeRetrievalEntry>(data.knowledgeRetrievalEvidence);
        entries.Sort(CompareKnowledgeDebugEntries);

        for (int i = 0; i < entries.Count; i++)
        {
            ContextRetriever.DebugKnowledgeRetrievalEntry evidence = entries[i];
            KnowledgeEntry entry = evidence != null ? evidence.entry : null;

            if (entry == null)
            {
                continue;
            }

            builder.AppendLine((evidence.includedByRetriever ? "RETRIEVED" : "SKIPPED") + ": " + SafeText(entry.id, "no id") + " / " + SafeText(entry.title, "no title"));
            builder.AppendLine("- allowed: " + BoolText(evidence.allowedForNpc));
            builder.AppendLine("- inContextSnapshot: " + BoolText(IndexOfKnowledgeEntry(data.snapshot, entry) >= 0));
            builder.AppendLine("- score: " + evidence.finalScore);
            builder.AppendLine("- activation sources:");
            builder.AppendLine("  - message_activation: " + BoolText(evidence.hasMessageActivation));
            builder.AppendLine("  - visible_state_activation: " + BoolText(evidence.hasVisibleStateActivation));
            builder.AppendLine("  - npc_state_activation: " + BoolText(evidence.hasNpcStateActivation));
            builder.AppendLine("  - world_event_activation: " + BoolText(evidence.hasWorldEventActivation));
            builder.AppendLine("  - world_state_activation: " + BoolText(evidence.hasWorldStateActivation));
            builder.AppendLine("  - local_activation: " + BoolText(evidence.hasLocalActivation));
            builder.AppendLine("- final reason: " + SafeText(evidence.finalDecisionReason, "No decision reason recorded."));
        }

        builder.AppendLine();
    }

    private static void AppendHardcodedVsDynamic(StringBuilder builder, TraceData data)
    {
        builder.AppendLine("=== HARDCODED VS DYNAMIC ===");

        if (string.IsNullOrEmpty(data.finalPrompt))
        {
            builder.AppendLine("NOT AVAILABLE: final prompt is empty.");
            builder.AppendLine();
            return;
        }

        builder.AppendLine("1. Hardcoded/static prompt template:");
        builder.AppendLine("This part is hardcoded prompt template.");
        builder.AppendLine("- system instruction");
        builder.AppendLine("- roleplay contract");
        builder.AppendLine("- out-of-world request handling");
        builder.AppendLine("- relevance filter");
        builder.AppendLine("- anti-hinting rules");
        builder.AppendLine("- response rules");
        builder.AppendLine("- NPC voice expectations");
        builder.AppendLine("- NPC-specific boundary behavior");
        builder.AppendLine("- example test cases");
        builder.AppendLine("- player knowledge ownership rules");
        builder.AppendLine("- final check before answering");
        builder.AppendLine("- NPC RESPONSE marker");
        builder.AppendLine("Hardcoded prompt template excerpt before runtime context:");
        builder.AppendLine(ExtractPromptPrefix(data.finalPrompt, "CURRENT NPC"));
        builder.AppendLine("Hardcoded prompt template excerpt after runtime context:");
        builder.AppendLine(ExtractPromptSection(data.finalPrompt, "FINAL CHECK BEFORE ANSWERING:", null));
        builder.AppendLine();

        builder.AppendLine("2. Dynamic runtime context:");
        builder.AppendLine("This part is runtime context inserted into the template.");
        builder.AppendLine("- NPCProfile data");
        builder.AppendLine("- PlayerState visible state and player-discovered facts");
        builder.AppendLine("- NPCState personal mood/trust/events for active NPC only");
        builder.AppendLine("- WorldState data");
        builder.AppendLine("- filtered WorldEventLog events");
        builder.AppendLine("- SceneContextObject data");
        builder.AppendLine("- Retrieved KnowledgeBase entries");
        builder.AppendLine("- Dialogue memory");
        builder.AppendLine("- Player message");
        builder.AppendLine("Dynamic runtime context excerpt:");
        builder.AppendLine(ExtractPromptRange(data.finalPrompt, "CURRENT NPC", "FINAL CHECK BEFORE ANSWERING:"));
        builder.AppendLine();
    }

    private static void AppendSourceCodeReferences(StringBuilder builder, TraceData data)
    {
        builder.AppendLine("=== SOURCE CODE REFERENCES ===");
        builder.AppendLine("- RuntimeChatUI: " + RuntimeChatUIPath + " / DrawInput() creates the [TRACE CONTEXT PIPELINE] button and Send() calls DialogueManager.SendPlayerMessage(text) for normal chat input.");
        builder.AppendLine("- DialogueManager: " + DialogueManagerPath + " / SendPlayerMessage(string text) calls ContextRetriever.BuildSnapshot(currentNpc, currentNpcTransform, text), stores LastContextSnapshot, builds LastGeneratedPrompt with PromptBuilder.BuildPrompt(snapshot), then calls llmClient.SendPrompt(LastGeneratedPrompt, ...).");
        builder.AppendLine("- ContextRetriever: " + ContextRetrieverPath + " / BuildSnapshot(...) fills ContextSnapshot.npcProfile, worldState, playerState, playerMessage, nearbyObjects, retrievedKnowledge, and recentDialogueHistory.");
        builder.AppendLine("- PromptBuilder: " + PromptBuilderPath + " / BuildPrompt(ContextSnapshot snapshot) reads the ContextSnapshot and appends hardcoded template sections plus dynamic runtime context sections.");
        builder.AppendLine("- OpenAIClient: " + OpenAIClientPath + " / SendPrompt(string prompt, Action<string> onResponse) sends the prompt to OpenAI when DialogueManager selected OpenAI.");
        builder.AppendLine("- MockLLMClient: " + MockLLMClientPath + " / SendPrompt(string prompt, Action<string> onResponse) consumes the prompt locally when Mock is selected or fallback is used.");
        builder.AppendLine("- Provider used in last response: " + GetLastActualProvider(data));
        builder.AppendLine();
    }

    private static void AppendAutomaticMarkerTest(StringBuilder builder, List<ValueTraceRow> rows)
    {
        builder.AppendLine("=== AUTOMATIC MARKER TEST ===");

        if (rows == null || rows.Count == 0)
        {
            builder.AppendLine("NOT AVAILABLE: no values were available to check.");
            builder.AppendLine();
            return;
        }

        for (int i = 0; i < rows.Count; i++)
        {
            ValueTraceRow row = rows[i];
            builder.AppendLine(row.marker + ": " + row.sourceObject + "." + row.sourceField);
        }

        builder.AppendLine();
    }

    private static List<ValueTraceRow> BuildValueRows(TraceData data)
    {
        List<ValueTraceRow> rows = new List<ValueTraceRow>();
        string prompt = data.finalPrompt ?? string.Empty;

        AddNpcProfileRows(rows, data, prompt);
        AddPlayerStateRows(rows, data, prompt);
        AddNpcStateRows(rows, data, prompt);
        AddWorldStateRows(rows, data, prompt);
        AddWorldEventRows(rows, data, prompt);
        AddSceneContextObjectRows(rows, data, prompt);
        AddKnowledgeEntryRows(rows, data, prompt);
        AddDialogueMemoryRows(rows, data, prompt);
        AddPlayerMessageRows(rows, data, prompt);

        return rows;
    }

    private static void AddNpcProfileRows(List<ValueTraceRow> rows, TraceData data, string prompt)
    {
        NPCProfile npc = data.currentNpc != null ? data.currentNpc : (data.snapshot != null ? data.snapshot.npcProfile : null);
        string sourceObject = npc != null ? "NPCProfile asset " + DescribeAsset(npc) : "NPCProfile";

        if (npc == null)
        {
            AddUnavailableRow(rows, sourceObject, "*", "snapshot.npcProfile", "NOT AVAILABLE: no current NPC profile.");
            return;
        }

        bool inSnapshot = data.snapshot != null && data.snapshot.npcProfile == npc;
        AddTraceRow(rows, prompt, sourceObject, "npcId", npc.npcId, "snapshot.npcProfile.npcId", "Id: " + npc.npcId, inSnapshot, null);
        AddTraceRow(rows, prompt, sourceObject, "npcName / displayName", npc.npcName, "snapshot.npcProfile.npcName", "Name: " + npc.npcName, inSnapshot, null);
        AddTraceRow(rows, prompt, sourceObject, "role", npc.role, "snapshot.npcProfile.role", "Role: " + npc.role, inSnapshot, null);
        AddTraceRow(rows, prompt, sourceObject, "personality", npc.personality, "snapshot.npcProfile.personality", "Personality: " + npc.personality, inSnapshot, null);
        AddTraceRow(rows, prompt, sourceObject, "backstory / background", npc.backstory, "snapshot.npcProfile.backstory", "Backstory: " + npc.backstory, inSnapshot, null);
        AddTraceRow(rows, prompt, sourceObject, "speakingStyle", npc.speakingStyle, "snapshot.npcProfile.speakingStyle", "Speaking Style: " + npc.speakingStyle, inSnapshot, null);
        AddListRows(rows, prompt, sourceObject, "knowledgeTags", npc.knowledgeTags, "snapshot.npcProfile.knowledgeTags", inSnapshot);
        AddListRows(rows, prompt, sourceObject, "knownFacts", npc.knownFacts, "snapshot.npcProfile.knownFacts", inSnapshot);
        AddListRows(rows, prompt, sourceObject, "relationships", npc.relationships, "snapshot.npcProfile.relationships", inSnapshot);
    }

    private static void AddPlayerStateRows(List<ValueTraceRow> rows, TraceData data, string prompt)
    {
        PlayerState playerState = data.playerState;
        string sourceObject = playerState != null ? "PlayerState component " + DescribeComponent(playerState) : "PlayerState";

        if (playerState == null)
        {
            AddUnavailableRow(rows, sourceObject, "*", "snapshot.playerState", "NOT AVAILABLE: PlayerState was not found.");
            return;
        }

        bool inSnapshot = data.snapshot != null && data.snapshot.playerState == playerState;
        AddTraceRow(rows, prompt, sourceObject, "currentRole", playerState.currentRole, "snapshot.playerState.currentRole", "Current Role: " + playerState.currentRole, inSnapshot, null);
        AddTraceRow(rows, prompt, sourceObject, "equippedOutfit", playerState.equippedOutfit, "snapshot.playerState.equippedOutfit", "Equipped Outfit: " + playerState.equippedOutfit, inSnapshot, null);
        AddTraceRow(rows, prompt, sourceObject, "visibleHeldItem", playerState.visibleHeldItem, "snapshot.playerState.visibleHeldItem", "Visible Held Item: " + playerState.visibleHeldItem, inSnapshot, null);
        AddListRows(rows, prompt, sourceObject, "visibleStatusTags", playerState.visibleStatusTags, "snapshot.playerState.visibleStatusTags", inSnapshot);
        AddListRows(rows, prompt, sourceObject, "knownFacts", playerState.knownFacts, "snapshot.playerState.knownFacts", inSnapshot);
        AddListRows(rows, prompt, sourceObject, "heldItems", playerState.heldItems, "snapshot.playerState.heldItems", inSnapshot);
        AddListRows(rows, prompt, sourceObject, "completedActions", playerState.completedActions, "snapshot.playerState.completedActions", inSnapshot);
    }

    private static void AddNpcStateRows(List<ValueTraceRow> rows, TraceData data, string prompt)
    {
        NPCState npcState = data.snapshot != null ? data.snapshot.npcState : null;

        if (npcState == null)
        {
            AddUnavailableRow(rows, "NPCState", "*", "snapshot.npcState", "SKIP: snapshot.npcState is empty.");
            return;
        }

        string sourceObject = "NPCState for active NPC " + SafeText(npcState.npcId, "unknown");
        AddTraceRow(rows, prompt, sourceObject, "npcId", npcState.npcId, "snapshot.npcState.npcId", "NPC Id: " + npcState.npcId, true, null);
        AddTraceRow(rows, prompt, sourceObject, "mood", npcState.mood, "snapshot.npcState.mood", "Mood: " + npcState.mood, true, null);
        AddTraceRow(rows, prompt, sourceObject, "trustToPlayer", npcState.trustToPlayer, "snapshot.npcState.trustToPlayer", "Trust To Player: " + npcState.trustToPlayer, true, null);
        AddListRows(rows, prompt, sourceObject, "personalEvents", npcState.personalEvents, "snapshot.npcState.personalEvents", true);
    }

    private static void AddWorldStateRows(List<ValueTraceRow> rows, TraceData data, string prompt)
    {
        WorldState worldState = data.worldState;
        string sourceObject = worldState != null ? "WorldState object " + DescribeComponent(worldState) : "WorldState";

        if (worldState == null)
        {
            AddUnavailableRow(rows, sourceObject, "*", "snapshot.worldState", "NOT AVAILABLE: WorldState was not found.");
            return;
        }

        bool inSnapshot = data.snapshot != null && data.snapshot.worldState == worldState;
        AddTraceRow(rows, prompt, sourceObject, "currentEvent", worldState.currentEvent, "snapshot.worldState.currentEvent", "Current Event: " + worldState.currentEvent, inSnapshot, null);
        AddTraceRow(rows, prompt, sourceObject, "villageMood", worldState.villageMood, "snapshot.worldState.villageMood", "Village Mood: " + worldState.villageMood, inSnapshot, null);
        AddTraceRow(rows, prompt, sourceObject, "churchBellMissing", worldState.churchBellMissing.ToString(), "snapshot.worldState.churchBellMissing", "Church Bell Missing: " + worldState.churchBellMissing, inSnapshot, null);
        AddTraceRow(rows, prompt, sourceObject, "miraSawStranger", worldState.miraSawStranger.ToString(), "snapshot.worldState.miraSawStranger", "Mira Saw Stranger: " + worldState.miraSawStranger, inSnapshot, null);
        AddTraceRow(rows, prompt, sourceObject, "borinInspectedBellCase", worldState.borinInspectedBellCase.ToString(), "snapshot.worldState.borinInspectedBellCase", "Borin Inspected Bell Case: " + worldState.borinInspectedBellCase, inSnapshot, null);
        AddTraceRow(rows, prompt, sourceObject, "anselmReportedBellMissing", worldState.anselmReportedBellMissing.ToString(), "snapshot.worldState.anselmReportedBellMissing", "Anselm Reported Bell Missing: " + worldState.anselmReportedBellMissing, inSnapshot, null);
        AddListRows(rows, prompt, sourceObject, "globalFacts", worldState.globalFacts, "snapshot.worldState.globalFacts", inSnapshot);
    }

    private static void AddWorldEventRows(List<ValueTraceRow> rows, TraceData data, string prompt)
    {
        if (data.snapshot == null || data.snapshot.recentRelevantEvents == null || data.snapshot.recentRelevantEvents.Count == 0)
        {
            AddUnavailableRow(rows, "WorldEventLog", "recentRelevantEvents", "snapshot.recentRelevantEvents", "SKIP: snapshot.recentRelevantEvents is empty.");
            return;
        }

        for (int i = 0; i < data.snapshot.recentRelevantEvents.Count; i++)
        {
            WorldEvent worldEvent = data.snapshot.recentRelevantEvents[i];

            if (worldEvent == null)
            {
                continue;
            }

            string sourceObject = "WorldEvent snapshot.recentRelevantEvents[" + i + "]";
            AddTraceRow(rows, prompt, sourceObject, "eventType", worldEvent.eventType, "snapshot.recentRelevantEvents[" + i + "].eventType", worldEvent.GetShortText(), true, null);
            AddTraceRow(rows, prompt, sourceObject, "targetNpcId", worldEvent.targetNpcId, "snapshot.recentRelevantEvents[" + i + "].targetNpcId", worldEvent.targetNpcId, true, null);
            AddTraceRow(rows, prompt, sourceObject, "locationObjectId", worldEvent.locationObjectId, "snapshot.recentRelevantEvents[" + i + "].locationObjectId", worldEvent.locationObjectId, true, null);
            AddTraceRow(rows, prompt, sourceObject, "description", worldEvent.description, "snapshot.recentRelevantEvents[" + i + "].description", worldEvent.description, true, null);
        }
    }

    private static void AddSceneContextObjectRows(List<ValueTraceRow> rows, TraceData data, string prompt)
    {
        if (data.sceneObjects == null || data.sceneObjects.Length == 0)
        {
            AddUnavailableRow(rows, "SceneContextObject", "*", "snapshot.nearbyObjects", "SKIP: no SceneContextObject components found.");
            return;
        }

        for (int i = 0; i < data.sceneObjects.Length; i++)
        {
            SceneContextObject contextObject = data.sceneObjects[i];

            if (contextObject == null)
            {
                continue;
            }

            int snapshotIndex = IndexOfSceneObject(data.snapshot, contextObject);
            bool inSnapshot = snapshotIndex >= 0;
            string sourceObject = "SceneContextObject component " + DescribeComponent(contextObject);
            string snapshotPrefix = inSnapshot ? "snapshot.nearbyObjects[" + snapshotIndex + "]" : "NOT IN ContextSnapshot.nearbyObjects";
            string note = inSnapshot ? null : "NOT USED IN FINAL PROMPT: this SceneContextObject was not included by ContextRetriever.FindNearbySceneObjects.";

            AddTraceRow(rows, prompt, sourceObject, "objectId", contextObject.objectId, snapshotPrefix + ".objectId", "Id: " + contextObject.objectId, inSnapshot, note);
            AddTraceRow(rows, prompt, sourceObject, "displayName", contextObject.displayName, snapshotPrefix + ".displayName", "Name: " + contextObject.displayName, inSnapshot, note);
            AddTraceRow(rows, prompt, sourceObject, "objectType", contextObject.objectType, snapshotPrefix + ".objectType", "Type: " + contextObject.objectType, inSnapshot, note);
            AddTraceRow(rows, prompt, sourceObject, "description", contextObject.description, snapshotPrefix + ".description", "Description: " + contextObject.description, inSnapshot, note);
            AddListRows(rows, prompt, sourceObject, "tags", contextObject.tags, snapshotPrefix + ".tags", inSnapshot);
            AddListRows(rows, prompt, sourceObject, "stateFacts", contextObject.stateFacts, snapshotPrefix + ".stateFacts", inSnapshot);
        }
    }

    private static void AddKnowledgeEntryRows(List<ValueTraceRow> rows, TraceData data, string prompt)
    {
        if (data.knowledgeEntries == null || data.knowledgeEntries.Count == 0)
        {
            AddUnavailableRow(rows, "KnowledgeEntry", "*", "snapshot.retrievedKnowledge", "SKIP: no KnowledgeEntry records found in KnowledgeBase.");
            return;
        }

        for (int i = 0; i < data.knowledgeEntries.Count; i++)
        {
            KnowledgeEntry entry = data.knowledgeEntries[i];

            if (entry == null)
            {
                continue;
            }

            int snapshotIndex = IndexOfKnowledgeEntry(data.snapshot, entry);
            bool inSnapshot = snapshotIndex >= 0;
            string sourceObject = "KnowledgeEntry " + SafeText(entry.id, "no id") + " / " + SafeText(entry.title, "no title");
            string snapshotPrefix = inSnapshot ? "snapshot.retrievedKnowledge[" + snapshotIndex + "]" : "NOT IN ContextSnapshot.retrievedKnowledge";
            string note = inSnapshot ? null : "NOT USED IN FINAL PROMPT: this KnowledgeEntry was not retrieved into ContextSnapshot.retrievedKnowledge.";

            AddTraceRow(rows, prompt, sourceObject, "id", entry.id, snapshotPrefix + ".id", "Id: " + entry.id, inSnapshot, note);
            AddTraceRow(rows, prompt, sourceObject, "title", entry.title, snapshotPrefix + ".title", "Title: " + entry.title, inSnapshot, note);
            AddTraceRow(rows, prompt, sourceObject, "text / content", entry.text, snapshotPrefix + ".text", "Text: " + entry.text, inSnapshot, note);
            AddListRows(rows, prompt, sourceObject, "tags", entry.tags, snapshotPrefix + ".tags", inSnapshot);
            AddListRows(rows, prompt, sourceObject, "knownByNpcIds", entry.knownByNpcIds, snapshotPrefix + ".knownByNpcIds", inSnapshot);
            AddListRows(rows, prompt, sourceObject, "relatedObjectIds", entry.relatedObjectIds, snapshotPrefix + ".relatedObjectIds", inSnapshot);
            AddTraceRow(rows, prompt, sourceObject, "importance", entry.importance.ToString(), snapshotPrefix + ".importance", "Importance: " + entry.importance, inSnapshot, note);
        }
    }

    private static void AddDialogueMemoryRows(List<ValueTraceRow> rows, TraceData data, string prompt)
    {
        if (data.snapshot == null || data.snapshot.recentDialogueHistory == null || data.snapshot.recentDialogueHistory.Count == 0)
        {
            AddUnavailableRow(rows, "Dialogue memory", "recentDialogueHistory", "snapshot.recentDialogueHistory", "SKIP: snapshot.recentDialogueHistory is empty.");
            return;
        }

        for (int i = 0; i < data.snapshot.recentDialogueHistory.Count; i++)
        {
            DialogueMessage message = data.snapshot.recentDialogueHistory[i];

            if (message == null)
            {
                continue;
            }

            string sourceObject = "DialogueMessage snapshot.recentDialogueHistory[" + i + "]";
            string line = SafeText(message.speaker, "Unknown") + ": " + SafeText(message.text, "...");
            AddTraceRow(rows, prompt, sourceObject, "speaker", message.speaker, "snapshot.recentDialogueHistory[" + i + "].speaker", line, true, null);
            AddTraceRow(rows, prompt, sourceObject, "text", message.text, "snapshot.recentDialogueHistory[" + i + "].text", line, true, null);
        }
    }

    private static void AddPlayerMessageRows(List<ValueTraceRow> rows, TraceData data, string prompt)
    {
        string sourceObject = "Player message";

        if (!string.IsNullOrEmpty(data.runtimeChatInput))
        {
            AddTraceRow(rows, prompt, sourceObject, "RuntimeChatUI.inputText", data.runtimeChatInput, "NOT IN ContextSnapshot until Send() calls DialogueManager.SendPlayerMessage(text)", data.runtimeChatInput, false, "NOT USED IN FINAL PROMPT: this is current UI text, not necessarily the last sent player message.");
        }
        else
        {
            AddTraceRow(rows, prompt, sourceObject, "RuntimeChatUI.inputText", data.runtimeChatInput, "NOT IN ContextSnapshot until Send() calls DialogueManager.SendPlayerMessage(text)", data.runtimeChatInput, false, null);
        }

        string snapshotField = data.snapshot != null ? "snapshot.playerMessage" : "NOT AVAILABLE: no ContextSnapshot.";
        AddTraceRow(rows, prompt, sourceObject, "current player input / last sent message", data.snapshot != null ? data.snapshot.playerMessage : data.lastPlayerMessage, snapshotField, data.snapshot != null ? data.snapshot.playerMessage : data.lastPlayerMessage, data.snapshot != null, null);
    }

    private static void AddListRows(List<ValueTraceRow> rows, string prompt, string sourceObject, string sourceField, List<string> values, string snapshotField, bool allowSearch)
    {
        if (values == null || values.Count == 0)
        {
            AddTraceRow(rows, prompt, sourceObject, sourceField, string.Empty, snapshotField, null, allowSearch, null);
            return;
        }

        bool wroteValue = false;

        for (int i = 0; i < values.Count; i++)
        {
            if (string.IsNullOrEmpty(values[i]) || values[i].Trim().Length == 0)
            {
                continue;
            }

            wroteValue = true;
            AddTraceRow(rows, prompt, sourceObject, sourceField + "[" + i + "]", values[i], snapshotField + "[" + i + "]", "- " + values[i].Trim(), allowSearch, allowSearch ? null : "NOT USED IN FINAL PROMPT: source object/list is not present in ContextSnapshot.");
        }

        if (!wroteValue)
        {
            AddTraceRow(rows, prompt, sourceObject, sourceField, string.Empty, snapshotField, null, allowSearch, null);
        }
    }

    private static void AddUnavailableRow(List<ValueTraceRow> rows, string sourceObject, string sourceField, string snapshotField, string note)
    {
        ValueTraceRow row = new ValueTraceRow();
        row.sourceObject = sourceObject;
        row.sourceField = sourceField;
        row.sourceValue = "NOT AVAILABLE";
        row.snapshotField = snapshotField;
        row.appearsInPrompt = "false";
        row.promptExcerpt = note;
        row.marker = note.StartsWith("SKIP", StringComparison.OrdinalIgnoreCase) ? note : "FAIL: " + note;
        row.note = note;
        rows.Add(row);
    }

    private static void AddTraceRow(List<ValueTraceRow> rows, string prompt, string sourceObject, string sourceField, string sourceValue, string snapshotField, string searchText, bool allowSearch, string note)
    {
        ValueTraceRow row = new ValueTraceRow();
        row.sourceObject = sourceObject;
        row.sourceField = sourceField;
        row.sourceValue = FormatValue(sourceValue);
        row.snapshotField = snapshotField;
        row.note = note;

        if (string.IsNullOrEmpty(sourceValue) || sourceValue.Trim().Length == 0)
        {
            row.appearsInPrompt = "false";
            row.promptExcerpt = "SKIP: value is empty/null.";
            row.marker = "SKIP: " + sourceField + " is empty.";
            rows.Add(row);
            return;
        }

        if (!allowSearch)
        {
            row.appearsInPrompt = "false";
            row.promptExcerpt = "NOT USED IN FINAL PROMPT.";
            row.marker = "FAIL: " + sourceField + " did not propagate into ContextSnapshot/final prompt.";
            rows.Add(row);
            return;
        }

        string effectiveSearchText = string.IsNullOrEmpty(searchText) ? sourceValue : searchText;

        if (string.IsNullOrEmpty(prompt))
        {
            row.appearsInPrompt = "false";
            row.promptExcerpt = "NOT AVAILABLE: final prompt is empty.";
            row.marker = "FAIL: " + sourceField + " could not be checked because final prompt is empty.";
            rows.Add(row);
            return;
        }

        if (ContainsNormalized(prompt, effectiveSearchText))
        {
            row.appearsInPrompt = "true";
            row.promptExcerpt = FindPromptExcerpt(prompt, effectiveSearchText);
            row.marker = "PASS: " + sourceField + " appeared in final prompt.";
        }
        else
        {
            row.appearsInPrompt = "false";
            row.promptExcerpt = "NOT USED IN FINAL PROMPT.";
            row.marker = "FAIL: " + sourceField + " did not appear in final prompt.";
        }

        rows.Add(row);
    }

    private static bool ContainsNormalized(string text, string searchText)
    {
        if (string.IsNullOrEmpty(text) || string.IsNullOrEmpty(searchText))
        {
            return false;
        }

        return NormalizeNewlines(text).Contains(NormalizeNewlines(searchText));
    }

    private static string FindPromptExcerpt(string prompt, string searchText)
    {
        if (string.IsNullOrEmpty(prompt) || string.IsNullOrEmpty(searchText))
        {
            return "NOT AVAILABLE: empty prompt or search text.";
        }

        string normalizedPrompt = NormalizeNewlines(prompt);
        string normalizedSearch = NormalizeNewlines(searchText);
        int index = normalizedPrompt.IndexOf(normalizedSearch, StringComparison.Ordinal);

        if (index < 0)
        {
            return "NOT USED IN FINAL PROMPT.";
        }

        int lineStart = normalizedPrompt.LastIndexOf('\n', Mathf.Max(0, index));
        lineStart = lineStart < 0 ? 0 : lineStart + 1;
        int lineEnd = normalizedPrompt.IndexOf('\n', index);
        lineEnd = lineEnd < 0 ? normalizedPrompt.Length : lineEnd;

        if (normalizedSearch.Contains("\n"))
        {
            return Clip(normalizedSearch, 500);
        }

        return Clip(normalizedPrompt.Substring(lineStart, lineEnd - lineStart), 500);
    }

    private static string ExtractPromptPrefix(string prompt, string endHeader)
    {
        string normalizedPrompt = NormalizeNewlines(prompt);
        int endIndex = FindHeaderIndex(normalizedPrompt, endHeader);

        if (endIndex < 0)
        {
            return "NEEDS MANUAL CHECK: header not found: " + endHeader;
        }

        return Clip(normalizedPrompt.Substring(0, endIndex).TrimEnd(), 4000);
    }

    private static string ExtractPromptRange(string prompt, string startHeader, string endHeader)
    {
        string normalizedPrompt = NormalizeNewlines(prompt);
        int startIndex = FindHeaderIndex(normalizedPrompt, startHeader);
        int endIndex = FindHeaderIndex(normalizedPrompt, endHeader);

        if (startIndex < 0)
        {
            return "NEEDS MANUAL CHECK: start header not found: " + startHeader;
        }

        if (endIndex < 0 || endIndex <= startIndex)
        {
            return Clip(normalizedPrompt.Substring(startIndex).TrimEnd(), 4000);
        }

        return Clip(normalizedPrompt.Substring(startIndex, endIndex - startIndex).TrimEnd(), 4000);
    }

    private static string ExtractPromptSection(string prompt, string sectionHeader, string nextSectionHeader)
    {
        string normalizedPrompt = NormalizeNewlines(prompt);
        int startIndex = FindHeaderIndex(normalizedPrompt, sectionHeader);

        if (startIndex < 0)
        {
            return "NEEDS MANUAL CHECK: section header not found: " + sectionHeader;
        }

        int endIndex = string.IsNullOrEmpty(nextSectionHeader) ? -1 : FindHeaderIndex(normalizedPrompt, nextSectionHeader);

        if (endIndex < 0 || endIndex <= startIndex)
        {
            return Clip(normalizedPrompt.Substring(startIndex).TrimEnd(), 4000);
        }

        return Clip(normalizedPrompt.Substring(startIndex, endIndex - startIndex).TrimEnd(), 4000);
    }

    private static int FindHeaderIndex(string text, string header)
    {
        if (string.IsNullOrEmpty(text) || string.IsNullOrEmpty(header))
        {
            return -1;
        }

        if (text.StartsWith(header + "\n", StringComparison.Ordinal) || text == header)
        {
            return 0;
        }

        int index = text.IndexOf("\n" + header + "\n", StringComparison.Ordinal);

        if (index >= 0)
        {
            return index + 1;
        }

        index = text.IndexOf("\n" + header, StringComparison.Ordinal);
        return index >= 0 ? index + 1 : -1;
    }

    private static string NormalizeNewlines(string value)
    {
        return string.IsNullOrEmpty(value) ? string.Empty : value.Replace("\r\n", "\n").Replace("\r", "\n");
    }

    private static string Clip(string value, int maxLength)
    {
        if (string.IsNullOrEmpty(value))
        {
            return "None";
        }

        if (value.Length <= maxLength)
        {
            return value;
        }

        return value.Substring(0, Mathf.Max(0, maxLength)) + "...";
    }

    private static int IndexOfSceneObject(ContextSnapshot snapshot, SceneContextObject contextObject)
    {
        if (snapshot == null || snapshot.nearbyObjects == null || contextObject == null)
        {
            return -1;
        }

        for (int i = 0; i < snapshot.nearbyObjects.Count; i++)
        {
            if (snapshot.nearbyObjects[i] == contextObject)
            {
                return i;
            }
        }

        return -1;
    }

    private static int IndexOfKnowledgeEntry(ContextSnapshot snapshot, KnowledgeEntry entry)
    {
        if (snapshot == null || snapshot.retrievedKnowledge == null || entry == null)
        {
            return -1;
        }

        for (int i = 0; i < snapshot.retrievedKnowledge.Count; i++)
        {
            if (snapshot.retrievedKnowledge[i] == entry)
            {
                return i;
            }
        }

        return -1;
    }

    private static List<KnowledgeEntry> GetKnowledgeEntries(ContextRetriever contextRetriever)
    {
        if (contextRetriever == null || contextRetriever.knowledgeBase == null)
        {
            return new List<KnowledgeEntry>();
        }

        return contextRetriever.knowledgeBase.GetAllEntries();
    }

    private static List<ContextRetriever.DebugKnowledgeRetrievalEntry> GetKnowledgeRetrievalEvidence(TraceData data)
    {
        if (data == null || data.contextRetriever == null || data.contextRetriever.knowledgeBase == null)
        {
            return new List<ContextRetriever.DebugKnowledgeRetrievalEntry>();
        }

        if (data.snapshot != null)
        {
            return data.contextRetriever.DebugExplainKnowledgeRetrieval(
                data.snapshot.npcProfile,
                data.snapshot.nearbyObjects,
                data.snapshot.playerMessage,
                data.snapshot.playerState,
                data.snapshot.worldState,
                data.snapshot.npcState,
                data.snapshot.recentRelevantEvents);
        }

        if (data.currentNpc != null)
        {
            string playerMessage = string.IsNullOrEmpty(data.lastPlayerMessage) ? data.runtimeChatInput : data.lastPlayerMessage;
            return data.contextRetriever.DebugExplainKnowledgeRetrieval(data.currentNpc, null, playerMessage);
        }

        return new List<ContextRetriever.DebugKnowledgeRetrievalEntry>();
    }

    private static int CompareKnowledgeDebugEntries(ContextRetriever.DebugKnowledgeRetrievalEntry a, ContextRetriever.DebugKnowledgeRetrievalEntry b)
    {
        if (a == null && b == null)
        {
            return 0;
        }

        if (a == null)
        {
            return 1;
        }

        if (b == null)
        {
            return -1;
        }

        int includedCompare = b.includedByRetriever.CompareTo(a.includedByRetriever);

        if (includedCompare != 0)
        {
            return includedCompare;
        }

        int scoreCompare = b.finalScore.CompareTo(a.finalScore);

        if (scoreCompare != 0)
        {
            return scoreCompare;
        }

        return string.Compare(GetKnowledgeSortName(a.entry), GetKnowledgeSortName(b.entry), StringComparison.OrdinalIgnoreCase);
    }

    private static string GetKnowledgeSortName(KnowledgeEntry entry)
    {
        if (entry == null)
        {
            return string.Empty;
        }

        return !string.IsNullOrEmpty(entry.title) ? entry.title : entry.id;
    }

    private static DialogueManager FindDialogueManager()
    {
        if (DialogueManager.Instance != null)
        {
            return DialogueManager.Instance;
        }

        return UnityEngine.Object.FindFirstObjectByType<DialogueManager>();
    }

    private static ContextRetriever ResolveContextRetriever()
    {
        if (ContextRetriever.Instance != null)
        {
            return ContextRetriever.Instance;
        }

        return UnityEngine.Object.FindFirstObjectByType<ContextRetriever>();
    }

    private static NPCConversationMemoryStore ResolveMemoryStore()
    {
        if (NPCConversationMemoryStore.Instance != null)
        {
            return NPCConversationMemoryStore.Instance;
        }

        return UnityEngine.Object.FindFirstObjectByType<NPCConversationMemoryStore>();
    }

    private static PlayerState FindPlayerState()
    {
        try
        {
            GameObject playerObject = GameObject.FindGameObjectWithTag("Player");

            if (playerObject != null)
            {
                PlayerState playerState = playerObject.GetComponent<PlayerState>();

                if (playerState != null)
                {
                    return playerState;
                }
            }
        }
        catch (UnityException)
        {
        }

        return UnityEngine.Object.FindFirstObjectByType<PlayerState>();
    }

    private static WorldState ResolveWorldState()
    {
        if (WorldState.Instance != null)
        {
            return WorldState.Instance;
        }

        return UnityEngine.Object.FindFirstObjectByType<WorldState>();
    }

    private static string BuildSnapshotUnavailableReason(ContextRetriever contextRetriever, NPCProfile currentNpc)
    {
        if (contextRetriever == null)
        {
            return "NOT AVAILABLE: ContextRetriever was not found.";
        }

        if (currentNpc == null)
        {
            return "NOT AVAILABLE: no current NPC is selected.";
        }

        return "NOT AVAILABLE: unknown snapshot build failure.";
    }

    private static string DescribeSnapshot(ContextSnapshot snapshot)
    {
        if (snapshot == null)
        {
            return "NOT AVAILABLE: ContextSnapshot is null.";
        }

        return "ContextSnapshot(npcProfile=" + DescribeNpc(snapshot.npcProfile) +
            ", playerState=" + (snapshot.playerState != null ? DescribeComponent(snapshot.playerState) : "None") +
            ", worldState=" + (snapshot.worldState != null ? DescribeComponent(snapshot.worldState) : "None") +
            ", npcState=" + (snapshot.npcState != null ? SafeText(snapshot.npcState.npcId, "None") : "None") +
            ", nearbyObjects=" + GetCountText(snapshot.nearbyObjects) +
            ", recentRelevantEvents=" + GetCountText(snapshot.recentRelevantEvents) +
            ", retrievedKnowledge=" + GetCountText(snapshot.retrievedKnowledge) +
            ", recentDialogueHistory=" + GetCountText(snapshot.recentDialogueHistory) +
            ", playerMessage=" + FormatValue(snapshot.playerMessage) + ")";
    }

    private static string DescribeNpc(NPCProfile npc)
    {
        if (npc == null)
        {
            return "None";
        }

        return SafeText(npc.npcId, "no id") + " / " + SafeText(npc.npcName, npc.name);
    }

    private static string DescribeKnowledgeBase(ContextRetriever contextRetriever)
    {
        if (contextRetriever == null)
        {
            return "NOT AVAILABLE: ContextRetriever is null.";
        }

        if (contextRetriever.knowledgeBase == null)
        {
            return "NOT AVAILABLE: ContextRetriever.knowledgeBase is not assigned.";
        }

        return DescribeAsset(contextRetriever.knowledgeBase);
    }

    private static string DescribeAsset(UnityEngine.Object asset)
    {
        if (asset == null)
        {
            return "NOT AVAILABLE: asset reference is null.";
        }

        string description = asset.GetType().Name + " '" + asset.name + "'";

#if UNITY_EDITOR
        string assetPath = AssetDatabase.GetAssetPath(asset);

        if (!string.IsNullOrEmpty(assetPath))
        {
            description += " at " + assetPath;
        }
#endif

        return description;
    }

    private static string DescribeComponent(Component component)
    {
        if (component == null)
        {
            return "NOT AVAILABLE: component reference is null.";
        }

        return component.GetType().Name + " on " + GetGameObjectPath(component.gameObject);
    }

    private static string DescribeTransform(Transform transform)
    {
        if (transform == null)
        {
            return "NOT AVAILABLE: Transform is null.";
        }

        return GetGameObjectPath(transform.gameObject);
    }

    private static string GetGameObjectPath(GameObject gameObject)
    {
        if (gameObject == null)
        {
            return "NOT AVAILABLE: GameObject is null.";
        }

        string path = gameObject.name;
        Transform current = gameObject.transform.parent;

        while (current != null)
        {
            path = current.name + "/" + path;
            current = current.parent;
        }

        return path;
    }

    private static string GetProviderClassName(TraceData data)
    {
        string actualProvider = GetLastActualProvider(data);

        if (actualProvider.IndexOf("Mock", StringComparison.OrdinalIgnoreCase) >= 0)
        {
            return "MockLLMClient";
        }

        if (actualProvider.IndexOf("OpenAI", StringComparison.OrdinalIgnoreCase) >= 0)
        {
            return "OpenAIClient";
        }

        if (data.dialogueManager != null && data.dialogueManager.DebugUseOpenAI && data.openAIClient != null)
        {
            return "OpenAIClient";
        }

        if (data.mockLLMClient != null)
        {
            return "MockLLMClient";
        }

        return "ILLMClient";
    }

    private static string GetProviderFilePath(TraceData data)
    {
        string providerClass = GetProviderClassName(data);

        if (providerClass == "OpenAIClient")
        {
            return OpenAIClientPath;
        }

        if (providerClass == "MockLLMClient")
        {
            return MockLLMClientPath;
        }

        return "NOT AVAILABLE: no provider file could be selected.";
    }

    private static string GetProviderResultText(TraceData data)
    {
        if (!data.promptWasActuallySent)
        {
            return "NOT AVAILABLE: the trace button did not call OpenAIClient or MockLLMClient. No provider send happened during this trace.";
        }

        if (data.openAIClient != null)
        {
            return "OpenAI success = " + data.openAIClient.LastOpenAIRequestSucceeded +
                "; Mock fallback used = " + data.openAIClient.LastMockFallbackUsed +
                "; HTTP status = " + data.openAIClient.LastHttpStatusCode +
                "; OpenAI LastActualProvider = " + SafeText(data.openAIClient.LastActualProvider, "None") + ".";
        }

        if (data.mockLLMClient != null)
        {
            return "Mock response generated = " + data.mockLLMClient.LastMockResponseGenerated +
                "; Mock LastActualProvider = " + SafeText(data.mockLLMClient.LastActualProvider, "None") + ".";
        }

        return "NOT AVAILABLE: no OpenAIClient or MockLLMClient reference is available.";
    }

    private static string GetProviderInputText(TraceData data)
    {
        if (!data.promptWasActuallySent)
        {
            return "Data enters: NOT AVAILABLE: no final prompt has been sent by DialogueManager yet, or this prompt was reconstructed for tracing only. Trace button does not call SendPrompt.";
        }

        return "Data enters: final prompt from DialogueManager.LastGeneratedPrompt; prompt length = " + GetLengthText(data.finalPrompt) + ".";
    }

    private static string GetLastIntendedProvider(TraceData data)
    {
        if (data.dialogueManager == null)
        {
            return "NOT AVAILABLE: DialogueManager is null.";
        }

        return SafeText(data.dialogueManager.LastIntendedLLMProvider, data.dialogueManager.CurrentLLMName);
    }

    private static string GetLastActualProvider(TraceData data)
    {
        if (data.dialogueManager == null)
        {
            return "NOT AVAILABLE: DialogueManager is null.";
        }

        return SafeText(data.dialogueManager.LastActualLLMProvider, "None");
    }

    private static string PromptEquals(string finalPrompt, string reconstructedPrompt)
    {
        if (string.IsNullOrEmpty(finalPrompt) || string.IsNullOrEmpty(reconstructedPrompt))
        {
            return "false (NOT AVAILABLE: one prompt string is empty)";
        }

        return string.Equals(NormalizeNewlines(finalPrompt), NormalizeNewlines(reconstructedPrompt), StringComparison.Ordinal) ? "true" : "false";
    }

    private static string GetCountText<T>(List<T> values)
    {
        return values != null ? values.Count.ToString() : "NOT AVAILABLE";
    }

    private static string GetLengthText(string value)
    {
        return value != null ? value.Length.ToString() : "NOT AVAILABLE";
    }

    private static string FormatValue(string value)
    {
        if (string.IsNullOrEmpty(value))
        {
            return "SKIP: empty/null";
        }

        return Clip(NormalizeNewlines(value), 500);
    }

    private static string SafeText(string value, string fallback)
    {
        return string.IsNullOrEmpty(value) || value.Trim().Length == 0 ? fallback : value;
    }

    private static string BoolText(bool value)
    {
        return value ? "true" : "false";
    }

    private static void SaveReport(string report)
    {
        try
        {
            Directory.CreateDirectory(Application.persistentDataPath);
            string fileName = "ContextPipelineTrace_" + DateTime.Now.ToString("yyyyMMdd_HHmmss") + ".txt";
            string filePath = Path.Combine(Application.persistentDataPath, fileName);
            File.WriteAllText(filePath, report, Encoding.UTF8);
            Debug.Log("CONTEXT PIPELINE TRACE REPORT saved to: " + filePath);
        }
        catch (Exception exception)
        {
            Debug.LogError("Failed to save CONTEXT PIPELINE TRACE REPORT: " + exception.Message);
        }
    }

    private class TraceData
    {
        public DialogueManager dialogueManager;
        public ContextRetriever contextRetriever;
        public NPCConversationMemoryStore memoryStore;
        public OpenAIClient openAIClient;
        public MockLLMClient mockLLMClient;
        public NPCProfile currentNpc;
        public Transform currentNpcTransform;
        public PlayerState playerState;
        public WorldState worldState;
        public SceneContextObject[] sceneObjects = new SceneContextObject[0];
        public List<KnowledgeEntry> knowledgeEntries = new List<KnowledgeEntry>();
        public List<ContextRetriever.DebugKnowledgeRetrievalEntry> knowledgeRetrievalEvidence = new List<ContextRetriever.DebugKnowledgeRetrievalEntry>();
        public ContextSnapshot snapshot;
        public string runtimeChatInput = string.Empty;
        public string lastPlayerMessage = string.Empty;
        public string finalPrompt = string.Empty;
        public string reconstructedPrompt = string.Empty;
        public string snapshotOrigin = string.Empty;
        public string finalPromptOrigin = string.Empty;
        public bool usedTraceOnlySnapshot;
        public bool promptWasActuallySent;
    }

    private class ValueTraceRow
    {
        public string sourceObject;
        public string sourceField;
        public string sourceValue;
        public string snapshotField;
        public string appearsInPrompt;
        public string promptExcerpt;
        public string marker;
        public string note;
    }
}
